const KEY_DOWN_ACTION = "KeyDown";
const KEY_UP_ACTION = "KeyUp";
const PLAYER_POSITION_CHANGED_ACTION = "PlayerPositionChanged";


export {KEY_DOWN_ACTION, KEY_UP_ACTION, PLAYER_POSITION_CHANGED_ACTION};