const KEY_PRESSED_ACTION = "KeyPressed";
const TIMESTEP_ACTION = "TimeStep";
const PLAYER_POSITION_CHANGED_ACTION = "PlayerPositionChanged";


export {KEY_PRESSED_ACTION, TIMESTEP_ACTION, PLAYER_POSITION_CHANGED_ACTION};